name: 04 - using action

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: printing Folders
              run: ls
            - name: setup Node
              uses: actions/setup-node@3
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm ci
        #1 ststall deps on our react application

    